import type { Metadata } from "next";

import localFont from "next/font/local";
import "./globals.css";
import { Header } from "@/ui/Header";
import { Footer } from "@/ui/Footer";
import { Form } from "@/ui/form/Form";

const gunterz = localFont({
  src: "../public/fonts/Gunterz-Regular.otf",
  variable: "--font-gunterz",
});
const gunterzBoldItalic = localFont({
  src: "../public/fonts/Gunterz-BoldItalic.otf",
  variable: "--font-gunterz-bold-italic",
});
const gunterzBold = localFont({
  src: "../public/fonts/Gunterz-Bold.otf",
  variable: "--font-gunterz-bold",
});

const gunterzItalic = localFont({
  src: "../public/fonts/Gunterz-MediumItalic.otf",
  variable: "--font-gunterz-medium-italic",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body
        className={`${gunterz.variable} ${gunterzBold.variable} ${gunterzBoldItalic.variable} ${gunterzItalic.variable}`}
      >
          <Header />
          {children}
          <Form />
          <Footer />
      </body>
    </html>
  );
}
