import type { Metadata } from "next";

import localFont from "next/font/local"
import "./globals.css";
import { Header } from "@/ui/Header"


const nobelUno = localFont({
  src: "../public/fonts/NobelUno-Regular.otf",
  variable: "--font-nobel-uno",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={nobelUno.className}><Header />{children}</body>
    </html>
  );
}
